package br.com.mobiew.siseve.model.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table( name = "cliente" )
public class Cliente implements Serializable {

	private static final long serialVersionUID = 4852817768073337899L;

	private Long id;

	private String nome;

	private Date dataNascimento;

	private String sexo;

	private String endereco;

	private String bairro;

	private String cidade;

	private String uf;

	private String telefone;

	private String email;

	private Set<Atendimento> atendimentos = new HashSet<Atendimento>( 0 );

	public Cliente() {
	}

	public Cliente( String nome ) {
		this.nome = nome;
	}

	public Cliente( String nome, Date dataNascimento, String sexo, String endereco, String bairro, String cidade, String uf, String telefone, String email,
			Set<Atendimento> atendimentos ) {
		this.nome = nome;
		this.dataNascimento = dataNascimento;
		this.sexo = sexo;
		this.endereco = endereco;
		this.bairro = bairro;
		this.cidade = cidade;
		this.uf = uf;
		this.telefone = telefone;
		this.email = email;
		this.atendimentos = atendimentos;
	}

	@Id
	@GeneratedValue( strategy = IDENTITY )

	@Column( name = "ID", unique = true, nullable = false )
	public Long getId() {
		return this.id;
	}

	public void setId( Long id ) {
		this.id = id;
	}

	@Column( name = "NOME", nullable = false, length = 100 )
	public String getNome() {
		return this.nome;
	}

	public void setNome( String nome ) {
		this.nome = nome;
	}

	@Temporal( TemporalType.DATE )
	@Column( name = "DATA_NASCIMENTO", length = 10 )
	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento( Date dataNascimento ) {
		this.dataNascimento = dataNascimento;
	}

	@Column( name = "SEXO", length = 2 )
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo( String sexo ) {
		this.sexo = sexo;
	}

	@Column( name = "ENDERECO", length = 200 )
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco( String endereco ) {
		this.endereco = endereco;
	}

	@Column( name = "BAIRRO", length = 45 )
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro( String bairro ) {
		this.bairro = bairro;
	}

	@Column( name = "CIDADE", length = 45 )
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade( String cidade ) {
		this.cidade = cidade;
	}

	@Column( name = "UF", length = 2 )
	public String getUf() {
		return this.uf;
	}

	public void setUf( String uf ) {
		this.uf = uf;
	}

	@Column( name = "TELEFONE", length = 45 )
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone( String telefone ) {
		this.telefone = telefone;
	}

	@Column( name = "EMAIL", length = 45 )
	public String getEmail() {
		return this.email;
	}

	public void setEmail( String email ) {
		this.email = email;
	}

	@OneToMany( fetch = FetchType.LAZY, mappedBy = "cliente" )
	public Set<Atendimento> getAtendimentos() {
		return this.atendimentos;
	}

	public void setAtendimentos( Set<Atendimento> atendimentos ) {
		this.atendimentos = atendimentos;
	}

}
