package br.com.mobiew.siseve.model.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.com.mobiew.siseve.util.DateUtil;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table( name = "cliente" )
public class Cliente implements Serializable {

	private static final long serialVersionUID = 4852817768073337899L;

	@Id
	@GeneratedValue( strategy = IDENTITY )
	@Column( name = "ID", unique = true, nullable = false )
	private Long id;

	@Column( name = "NOME", nullable = false, length = 100 )
	private String nome;

	@Temporal( TemporalType.DATE )
	@Column( name = "DATA_NASCIMENTO", length = 10 )
	private Date dataNascimento;

	@Column( name = "SEXO", length = 2 )
	private String sexo;

	@Column( name = "ENDERECO", length = 200 )
	private String endereco;

	@Column( name = "BAIRRO", length = 45 )
	private String bairro;

	@Column( name = "CIDADE", length = 45 )
	private String cidade;

	@Column( name = "UF", length = 2 )
	private String uf;

	@Column( name = "TELEFONE", length = 45 )
	private String telefone;

	@Column( name = "EMAIL", length = 45 )
	private String email;

    @OneToMany( fetch = FetchType.EAGER, cascade = CascadeType.ALL, mappedBy = "cliente", orphanRemoval = true )
	private Set<Atendimento> atendimentos = new HashSet<Atendimento>( 0 );

	public Cliente() {
		//
	}

	public Cliente( String nome ) {
		this.nome = nome;
	}

	public Long getId() {
		return this.id;
	}

	public void setId( Long id ) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome( String nome ) {
		this.nome = nome;
	}

	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento( Date dataNascimento ) {
		this.dataNascimento = dataNascimento;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo( String sexo ) {
		this.sexo = sexo;
	}

	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco( String endereco ) {
		this.endereco = endereco;
	}

	public String getBairro() {
		return this.bairro;
	}

	public void setBairro( String bairro ) {
		this.bairro = bairro;
	}

	public String getCidade() {
		return this.cidade;
	}

	public void setCidade( String cidade ) {
		this.cidade = cidade;
	}

	public String getUf() {
		return this.uf;
	}

	public void setUf( String uf ) {
		this.uf = uf;
	}

	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone( String telefone ) {
		this.telefone = telefone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail( String email ) {
		this.email = email;
	}

	public Set<Atendimento> getAtendimentos() {
		return this.atendimentos;
	}

	public void setAtendimentos( Set<Atendimento> atendimentos ) {
		this.atendimentos = atendimentos;
	}

	public Integer getIdade() {
        Integer idade = null;
        if ( this.dataNascimento != null ) {
            idade = DateUtil.diffDate( this.dataNascimento, new Date(), 3 );
        }
        return idade;
    }

	public List<Atendimento> getListAtendimentos() {
        return new ArrayList<Atendimento>( this.atendimentos );
    }
}
