package br.com.mobiew.siseve.model.entity;


import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table( name = "evento" )
public class Evento implements Serializable {

	private static final long serialVersionUID = -7137946645292507308L;
	
	@Id
	@GeneratedValue( strategy = IDENTITY )
	@Column( name = "ID", unique = true, nullable = false )
	private Long id;

	@Column( name = "NOME", nullable = false, length = 100 )
	private String nome;

	@Temporal( TemporalType.DATE )
	@Column( name = "DATA_INICIO", nullable = false, length = 10 )
	private Date dataInicio;

	@Temporal( TemporalType.DATE )
	@Column( name = "DATA_FIM", length = 10 )
	private Date dataFim;

	@Column( name = "LOCAL", length = 200 )
	private String local;

	@OneToMany( fetch = FetchType.LAZY, mappedBy = "evento" )
	private Set<Servico> servicos = new HashSet<Servico>( 0 );

	public Evento() {
		//
	}

	public Evento( String nome, Date dataInicio ) {
		this.nome = nome;
		this.dataInicio = dataInicio;
	}

	public Evento( String nome, Date dataInicio, Date dataFim, String local, Set<Servico> servicos ) {
		this.nome = nome;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
		this.local = local;
		this.servicos = servicos;
	}

	public Long getId() {
		return this.id;
	}

	public void setId( Long id ) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome( String nome ) {
		this.nome = nome;
	}

	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio( Date dataInicio ) {
		this.dataInicio = dataInicio;
	}

	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim( Date dataFim ) {
		this.dataFim = dataFim;
	}

	public String getLocal() {
		return this.local;
	}

	public void setLocal( String local ) {
		this.local = local;
	}

	public Set<Servico> getServicos() {
		return this.servicos;
	}

	public void setServicos( Set<Servico> servicos ) {
		this.servicos = servicos;
	}

}
