package br.com.mobiew.siseve.model.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.com.mobiew.siseve.util.Constantes;

/**
 * Profissional generated by hbm2java
 */
@Entity
@Table( name = "profissional" )
public class Profissional implements Serializable, Comparable<Profissional> {

	private static final long serialVersionUID = 7834335018485901190L;

	@Id
	@GeneratedValue( strategy = IDENTITY )
	@Column( name = "ID", unique = true, nullable = false )
	private Long id;

	@Column( name = "NOME", nullable = false, length = 100 )
	private String nome;

	@OneToMany( fetch = FetchType.LAZY, mappedBy = "profissional" )
	private Set<Atendimento> atendimentos = new HashSet<Atendimento>( 0 );

	public Profissional() {
		//
	}

	public Profissional( String nome ) {
		this.nome = nome;
	}

	public Profissional( String nome, Set<Atendimento> atendimentos ) {
		this.nome = nome;
		this.atendimentos = atendimentos;
	}

	public Long getId() {
		return this.id;
	}

	public void setId( Long id ) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome( String nome ) {
		this.nome = nome;
	}

	public Set<Atendimento> getAtendimentos() {
		return this.atendimentos;
	}

	public void setAtendimentos( Set<Atendimento> atendimentos ) {
		this.atendimentos = atendimentos;
	}

	@Override
	public int compareTo( Profissional oParam ) {
        String nomeNovo = this.getNome() == null ? "" : this.getNome();
        return Constantes.COLLATOR.compare( nomeNovo, oParam.getNome() );
    }

}
