package br.com.mobiew.siseve.model.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.com.mobiew.siseve.model.enuns.TipoRelatorioEnum;

/**
 * Servico generated by hbm2java
 */
@Entity
@Table( name = "servico" )
public class Servico implements Serializable {

	private static final long serialVersionUID = -3472895763433507107L;

	@Id
	@GeneratedValue( strategy = IDENTITY )
	@Column( name = "ID", unique = true, nullable = false )
	private Long id;

	@ManyToOne( fetch = FetchType.LAZY )
	@JoinColumn( name = "ID_EVENTO", nullable = false )
	private Evento evento;

	@Column( name = "NOME", nullable = false, length = 100 )
	private String nome;

	@Enumerated( EnumType.STRING )
	@Column( name = "TIPO_RELATORIO", length = 7 )
	private TipoRelatorioEnum tipoRelatorio;

	@OneToMany( fetch = FetchType.LAZY, mappedBy = "servico" )
	private Set<Atendimento> atendimentos = new HashSet<Atendimento>( 0 );

	public Servico() {
		//
	}

	public Servico( Evento evento, String nome ) {
		this.evento = evento;
		this.nome = nome;
	}

	public Long getId() {
		return this.id;
	}

	public void setId( Long id ) {
		this.id = id;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento( Evento evento ) {
		this.evento = evento;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome( String nome ) {
		this.nome = nome;
	}

	public Set<Atendimento> getAtendimentos() {
		return this.atendimentos;
	}

	public void setAtendimentos( Set<Atendimento> atendimentos ) {
		this.atendimentos = atendimentos;
	}

	public TipoRelatorioEnum getTipoRelatorio() {
		return this.tipoRelatorio;
	}

	public void setTipoRelatorio( TipoRelatorioEnum tipoRelatorioParam ) {
		this.tipoRelatorio = tipoRelatorioParam;
	}

}
