package br.com.mobiew.siseve.model.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table( name = "usuario", catalog = "siseve" )
public class Usuario implements Serializable {

	private static final long serialVersionUID = -7361804736252805773L;

	@Id
	@GeneratedValue( strategy = IDENTITY )
	@Column( name = "ID", unique = true, nullable = false )
	private Long id;

	@Column( name = "CD_LOGIN", nullable = false, length = 10 )
	private String cdLogin;

	@Column( name = "CD_SENHA", length = 8 )
	private String cdSenha;

	@Column( name = "NM_USUARIO", nullable = false, length = 100 )
	private String nmUsuario;

	@Column( name = "CD_IND_ADMINISTRADOR", length = 2 )
	private String cdIndAdministrador;

	public Usuario() {
		//
	}

	public Usuario( String cdLogin, String nmUsuario ) {
		this.cdLogin = cdLogin;
		this.nmUsuario = nmUsuario;
	}

	public Usuario( String cdLogin, String cdSenha, String nmUsuario, String cdIndAdministrador ) {
		this.cdLogin = cdLogin;
		this.cdSenha = cdSenha;
		this.nmUsuario = nmUsuario;
		this.cdIndAdministrador = cdIndAdministrador;
	}

	public Long getId() {
		return this.id;
	}

	public void setId( Long id ) {
		this.id = id;
	}

	public String getCdLogin() {
		return this.cdLogin;
	}

	public void setCdLogin( String cdLogin ) {
		this.cdLogin = cdLogin;
	}

	public String getCdSenha() {
		return this.cdSenha;
	}

	public void setCdSenha( String cdSenha ) {
		this.cdSenha = cdSenha;
	}

	public String getNmUsuario() {
		return this.nmUsuario;
	}

	public void setNmUsuario( String nmUsuario ) {
		this.nmUsuario = nmUsuario;
	}

	public String getCdIndAdministrador() {
		return this.cdIndAdministrador;
	}

	public void setCdIndAdministrador( String cdIndAdministrador ) {
		this.cdIndAdministrador = cdIndAdministrador;
	}

}
